# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
from openerp import api, fields, models

class Persona(models.Model):
    """Modelo que se utiliza para registrar los datos basicos de cada participante del curso"""
    _name = 'regtil.persona'
    _rec_name = 'cedula'
    cedula = fields.Integer(string='Cedula', help='Ingrese su cédula en el formato 16123123')
    primer_nombre = fields.Char(string= 'Primer Nombre', help='Ingrese su primer nombre. Ejemplo: Crisbel')
    segundo_nombre = fields.Char(string= 'Segundo Nombre', help='Ingrese su segundo nombre Ejemplo: Francisas')
    primer_apellido = fields.Char(string= 'Primer apellido', help='Ingrese su Primer apellido Ejemplo: Pinzon')
    segundo_apellido = fields.Char(string='Segundo Apellido', help='Ingrese su segundo Apellido Ejemplo: Villarroel')
    sexo = fields.Selection([('M','Masculino'),('F','Femenino')], string='Sexo', help='Seleccione su sexo')
    fecha_nacimiento = fields.Date(string='Fecha de Nacimiento', help='Selecciones su fecha de nacimiento. Seleccionando la fecha en el asistente o escribiendola en el formato 01/01/1999')
    direccion = fields.Text('Dirección', help='Ingrese su direccion de habitación')
    telefono = fields.Char(string='Télefono', help='Ingrese su télefono en el formato 0414-9355744')
    correo = fields.Char(string='Correo Electronico', help='Ingrese su correo electronico en el formato ejempli@ejemplo.com')
    #tipo_vinculacion_til = fields.Selection([('A','Activista'),('U','Usuario'),('P','Productor')], string ='Vinculacion Tecnologica' , help='Ingrese su vinculacion tecnologica')
    vinculacion_til_id = fields.Many2one('regtil.tipo_vinculacion_til', string ='Vinculacion TIL' , help='Selección el Tipo de Vinculacion con las TIL')
    state_id = fields.Many2one('res.country.state', string='Estado')
    municipality_id = fields.Many2one('res.country.state.municipality', string='Municipio')
    parish_id = fields.Many2one('res.country.state.municipality.parish', string='Parroquia')
    vivienda_ids = fields.One2many('regtil.vivienda', 'persona_id',string='Información de Vivienda')
    socio_economico_ids = fields.One2many('regtil.socio_economico','persona_ids',string='socio_economico')
    unidad_productiva_ids = fields.Many2many('regtil.unidad_productiva',string='Unidad productiva')

class TipoVinculacionTIL(models.Model):
    """Tipo de Vinculación con las Tecnologías Libres"""
    _name = 'regtil.tipo_vinculacion_til'
    name = fields.Char('Nombre')
    description = fields.Text('Descripción')

class Vivienda(models.Model):
    """Registro vivienda clase persona"""
    _name = 'regtil.vivienda'
    _rec_name = 'fecha_registro'
    fecha_registro = fields.Date(string='Fecha de Registro', help='Selecciones su fecha de registro', default=fields.Datetime.now)
    tipo_id = fields.Many2one('regtil.vivienda.tipo', string='Tipo', help='seleccione el tipo de vivienda actual')
    tenencia_id = fields.Many2one('regtil.vivienda.tenencia', string='Tenencia', help='Seleccione el tipo de tenencia de su viviend')
    condicion_id = fields.Many2one('regtil.vivienda.condicion', string='Condicion', help='Seleccione la condicion de la vivienda ')
    tiene_television = fields.Boolean(string='¿Tiene Television?', help='la persona tildará si posee television')
    tiene_computadora = fields.Boolean(string='¿Tiene Computadora?', help='la persona tildará si posee computadora')
    tiene_internet = fields.Boolean(string='¿Tiene Internet=', help='la persona tildará si posee internet')
    persona_id = fields.Many2one('persona',string='Persona')

class ViviendaTipo(models.Model):
    """Condición de la vivienda"""
    _name="regtil.vivienda.tipo"
    name = fields.Char('Nombre')
    description = fields.Text('Descripción')

class ViviendaTenencia(models.Model):
    """Condición de la vivienda"""
    _name="regtil.vivienda.tenencia"
    name = fields.Char('Nombre')
    description = fields.Text('Descripción')

class ViviendaCondicion(models.Model):
    """Condición de la vivienda"""
    _name="regtil.vivienda.condicion"
    name = fields.Char('Nombre')
    description = fields.Text('Descripción')

class SocioEconomico(models.Model):
    """registra el nivel socio ecnonomico de la persona"""
    _name = 'regtil.socio_economico'
    _rec_name = 'ingreso_mensual'
    discapacidad = fields.Boolean(string='¿posee alguna discapacidad?', help='la persona nombrara si tiene alguna discapacidad')
    cantidad_hijos= fields.Selection([('O','Ninguno'),('I','Uno'),('II','Dos'),('III','Tres'),('IV','Cuatro'),('Mas','Mas de 4')], help='la persona indicara si tiene hijos')
    grupo_familiar = fields.Selection([('II','Dos'),('III','Tres'),('IV','Cuatro'),('V','Cinco'),('Ma','Mas 5')],string='Grupo Familiar', help='La persona podra espicificar su carga familiar')
    ingreso_mensual = fields.Float(string='Ingreso Mensual', help='La persona indicara su ingreso mensual')
    trabaja = fields.Boolean(string='¿Trabaja actualmente?', help='la persona indacara si posee trabajo')
    estado_civil =fields.Selection([('S','Soltero(a)'),('C','Casado(a)'),('Se','Separado(a)'),('Di','Divorciado(a)'),('Vi','Viudo(a)')],string='Estado civil', help='La persona podra espicificar el estado civil')
    persona_ids = fields.Many2one('persona',string='persona')
    ocupacion_id = fields.Many2one('ocupacion',string='Ocupacion', help='Seleccione su Ocupacion ')
    grado_instruccion_id= fields.Many2one('grado_instruccion',string='Grado instruccion', help='Seleccione su grado_instruccion ')
    

class UnidadProductiva(models.Model):
    """la persona registra su inidad productiva"""
    _name = 'regtil.unidad_productiva'
    _rec_name = 'nombre'
    nombre = fields.Char(string='Nombre de la unidad productiva', help='la persona podra colocar el nombre de su unidad productiva')
    rif = fields.Integer(string='Rif', help='Ingrese su cedula en el formato 12345678-9')
    correo = fields.Char(string='Correo Electronico', help='Ingrese su correo electronico en el formato ejempli@ejemplo.com')
    facebook = fields.Char(string='Facebook', help='Ingrese su facebook con el nombre de su unidad profuctivad')
    twitter = fields.Char(string='Twitter', help='Ingrese su twitter con el nombre de su unidad profuctivad')
    tipo_industria = fields.Selection([('G','Grupal'),('F','Freelance'),('C','Cooperativa')], string='Tipo', help='la persona indicara el tipo de industria')
    servicio = fields.Char(string='¿Que servicio presta ', help='Ingresa el servicio que presta la unidad productiva')
    personas_ids = fields.Many2many('persona', string='Persona')
    tecnologia_ids = fields.Many2many('tecnologia', string='Tecnologia')

class Tecnologia(models.Model):
    """Modelo que registra la tecnologia"""
    _name = 'regtil.tecnologia'
    #_rec_name = 'tecnologia'
    tecnologia_domina = fields.Char(string='Tecnologia que domina', help='Ingresar la tecnologia que domina')
    uso_diario = fields.Char(string='cual es el uso diario ', help='Ingresar el uso diario de la tecnologia que domina ')
    unidad_productiva_ids = fields.Many2many('unidad_productiva',string='Unidad productiva')

class Ocupacion(models.Model):
    """Modelo que registra profesion de la persona"""
    _name = 'regtil.ocupacion'
    #_rec_name = 'tecnologia'
    ocupacion_personal = fields.Char(string='Cual es su ocupacion', help='la persona podra colocar la ocupacion acual')

class GradoInstruccion(models.Model):
    """Modelo que registra profesion de la persona"""
    _name = 'regtil.grado_instruccion'
    #_rec_name = 'tecnologia'
    grado_instruccion_personal = fields.Char(string='Cual es su grado instruccion', help='la persona podra colocar el grado_instruccion acual')